// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB38yBz3pPe21GvUBEtio4Jnb-l3PxEq4E',
    appId: '1:74212545508:web:f1d7e8c2852bd2e62fadf1',
    messagingSenderId: '74212545508',
    projectId: 'fitness-assessment-15f6f',
    authDomain: 'fitness-assessment-15f6f.firebaseapp.com',
    databaseURL: 'https://fitness-assessment-15f6f-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-assessment-15f6f.appspot.com',
    measurementId: 'G-HDR9V0ND16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2NHqTK6Ln9WehF8sip5mzN708uMR6b0',
    appId: '1:74212545508:android:185c3984068f9dbc2fadf1',
    messagingSenderId: '74212545508',
    projectId: 'fitness-assessment-15f6f',
    databaseURL: 'https://fitness-assessment-15f6f-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-assessment-15f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ2mKsUxo0Sl6Xpja3-riD4WqZZjhiyoI',
    appId: '1:74212545508:ios:44cecc42b82c75ac2fadf1',
    messagingSenderId: '74212545508',
    projectId: 'fitness-assessment-15f6f',
    databaseURL: 'https://fitness-assessment-15f6f-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-assessment-15f6f.appspot.com',
    iosBundleId: 'com.example.fitnessAssign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ2mKsUxo0Sl6Xpja3-riD4WqZZjhiyoI',
    appId: '1:74212545508:ios:44cecc42b82c75ac2fadf1',
    messagingSenderId: '74212545508',
    projectId: 'fitness-assessment-15f6f',
    databaseURL: 'https://fitness-assessment-15f6f-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-assessment-15f6f.appspot.com',
    iosBundleId: 'com.example.fitnessAssign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB38yBz3pPe21GvUBEtio4Jnb-l3PxEq4E',
    appId: '1:74212545508:web:5fdb590a776aa7ac2fadf1',
    messagingSenderId: '74212545508',
    projectId: 'fitness-assessment-15f6f',
    authDomain: 'fitness-assessment-15f6f.firebaseapp.com',
    databaseURL: 'https://fitness-assessment-15f6f-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-assessment-15f6f.appspot.com',
    measurementId: 'G-RR0CQW81MN',
  );
}
